### create game
POST {{url}}/game
Content-Type: application/json

{
"game": "{{game}}",
"password": "{{gamePassword}}",
"roundTime": 5
}

### start game
POST {{url}}/game/{{game}}/start
Content-Type: application/json

### register player
POST {{url}}/game/{{game}}/player
Content-Type: application/json

{
  "player": "{{player}}",
  "playerPassword": "{{playerPassword}}",
  "gamePassword": "{{gamePassword}}"
}

### register player move
POST {{url}}/game/{{game}}/player/{{player}}/move
Content-Type: application/json

{
  "x": 2,
  "y": 2
}

### get player situation
GET {{url}}/game/{{game}}/player/{{player}}
Accept: application/json

### accept bottle
POST {{url}}/game/{{game}}/player/{{player}}/event?type=BOTTLE
Accept: application/json

{
  "type": "BOTTLE",
  "accept": true
}
